/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "surface": "#f8f9fa",
              "surface-container-high": "#e7e8e9",
              "on-secondary": "#ffffff",
              "on-tertiary-container": "#e5fbfe",
              "primary-fixed-dim": "#b3c5ff",
              "secondary": "#4c5e85",
              "inverse-surface": "#2e3132",
              "outline-variant": "#c2c6d8",
              "on-primary-container": "#f7f6ff",
              "surface-tint": "#0054d7",
              "secondary-fixed-dim": "#b4c6f3",
              "surface-container-low": "#f3f4f5",
              "on-secondary-fixed": "#051a3e",
              "on-surface": "#191c1d",
              "inverse-on-surface": "#f0f1f2",
              "surface-variant": "#e1e3e4",
              "tertiary-fixed-dim": "#b5cacd",
              "on-surface-variant": "#424656",
              "on-error-container": "#93000a",
              "error-container": "#ffdad6",
              "tertiary": "#485c5f",
              "surface-dim": "#d9dadb",
              "primary-fixed": "#dbe1ff",
              "on-secondary-fixed-variant": "#35466c",
              "on-error": "#ffffff",
              "on-tertiary": "#ffffff",
              "inverse-primary": "#b3c5ff",
              "surface-container": "#edeeef",
              "primary-container": "#0065ff",
              "on-tertiary-fixed": "#0a1e21",
              "on-primary-fixed": "#00184a",
              "background": "#f8f9fa",
              "surface-container-lowest": "#ffffff",
              "tertiary-container": "#617578",
              "outline": "#727687",
              "on-secondary-container": "#485980",
              "surface-container-highest": "#e1e3e4",
              "primary": "#004fcb",
              "surface-bright": "#f8f9fa",
              "on-primary": "#ffffff",
              "secondary-container": "#bfd1ff",
              "on-primary-fixed-variant": "#003fa5",
              "error": "#ba1a1a",
              "on-tertiary-fixed-variant": "#364a4d",
              "on-background": "#191c1d",
              "secondary-fixed": "#d8e2ff",
              "tertiary-fixed": "#d1e7e9"
      },
      "borderRadius": {
              "DEFAULT": "12px",
              "sm": "8px",
              "md": "12px",
              "lg": "16px",
              "xl": "24px",
              "2xl": "32px",
              "full": "9999px"
      },
      "spacing": {
              "md": "16px",
              "unit": "4px",
              "gutter": "12px",
              "xs": "4px",
              "lg": "24px",
              "xl": "32px",
              "sm": "8px",
              "container-padding": "20px"
      },
      "fontFamily": {
              "sans": ["Inter", "sans-serif"],
              "inter": ["Inter", "sans-serif"],
              "label-bold": ["Inter"],
              "headline-xl": ["Inter"],
              "headline-md": ["Inter"],
              "body-md": ["Inter"],
              "label-sm": ["Inter"],
              "body-lg": ["Inter"]
      },
      "fontSize": {
              "label-bold": ["12px", {"lineHeight": "16px", "fontWeight": "700"}],
              "headline-xl": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "headline-md": ["20px", {"lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
              "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
              "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
              "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
