# Generated by Django 5.2.6 on 2026-04-24 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0004_invitation_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='assigned_members',
            field=models.ManyToManyField(blank=True, related_name='assigned_cards', to=settings.AUTH_USER_MODEL),
        ),
    ]
