# Generated by Django 6.0.4 on 2026-04-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0007_list_wip_limit_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
