# Generated by Django 5.2.6 on 2026-04-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0009_list_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='background_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='background_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
