# Generated by Django 5.2.6 on 2026-04-29 08:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0012_remove_card_assigned_members_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='workspaces', through='kanban.WorkspaceMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
