# Generated by Django 5.2.6 on 2026-05-05 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0013_workspace_members'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
