# Generated by Django 5.2.6 on 2026-05-11 12:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0015_workspacemember_last_active_activity_presence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='card',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
