# Generated by Django 5.2.6 on 2026-05-12 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0016_remove_card_assigned_to_card_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('doing', 'Doing'), ('completed', 'Completed')], default='todo', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='kanban.list'),
        ),
    ]
